name = "plplotlib"
version = "0.0.1"
maintainer = "PlPlotLib developers"
license = "LGPL v2.1"
keywords = "plotting"

[build]
link = "plplot"


[dev-dependencies]
test-drive = { git="https://github.com/fortran-lang/test-drive", tag="v0.4.0" }